name: .NET Core and Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Lint for C# -> dotnet format
    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format

    - name: Run dotnet format
      run: dotnet format 

    # SonarLint Analysis
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=maalcantara_dotnet-webapp
          -Dsonar.organization=maalcantara
          -X
        projectBaseDir: .

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: ./publish

  build-docker:
    runs-on: ubuntu-latest
    needs: build-dotnet

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dotnetappantigo-image:latest

    - name: Save Docker image to a tar file
      run: docker save -o dotnetappantigo-image.tar dotnetappantigo-image:latest

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: docker-image
        path: dotnetappantigo-image.tar
        if-no-files-found: error
        retention-days: 30
        compression-level: 6
        overwrite: true